name: "Publishing Package"

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0
      - uses: actions/setup-node@v1
        with:
          node-version: 10.x
      - run: npm i -g yarn@1.13.0
      - run: yarn --frozen-lockfile
      - run: yarn test:ci

  publish:
    needs: build
    runs-on: ubuntu-latest
    env:
      NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0
      - uses: actions/setup-node@v1
        with:
          node-version: 10.x
          registry-url: https://registry.npmjs.org/
      - run: npm i -g yarn@1.13.0
      - run: yarn --forzen-lockfile
      - run: yarn release
